# Generated by Django 4.2.16 on 2024-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
